title: ONPUKUN's JINKELA Session
description: 我举双手支持金坷垃文艺复兴！
theme: just-the-docs

url: 

logo: "/assets/images/Jinkela_head.png"

color_scheme: jinkela

search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false
  focus_shortcut_key: 'k'
  
mermaid:
  version: "9.1.3"

nav_enabled: true
nav_sort: default

heading_anchors: true

enable_copy_code_button: true

back_to_top: true
back_to_top_text: "返回页顶"

collections:
  jkl:
    output: true
    permalink: /:collection/:path/
  allstars:
    output: true
    permalink: /:collection/:path/
  others:
    output: true
    permalink: /:collection/:path/
    
just_the_docs:
  collections:
    jkl:
      name: 金坷垃
      nav_fold: true
    allstars:
      name: 全明星
      nav_fold: true
    others:
      name: 其他
      nav_fold: true

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: 提示
    color: blue
  new:
    title: 更新！
    color: green
  note:
    title: 说明
    color: purple
  warning:
    title: 高能预警
    color: red

